Partenaireailes:
    type: entity
    table: PartenaireAiles
    id:
        nom:
            type: string
            nullable: false
            length: 25
            fixed: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        logo:
            type: string
            nullable: false
            length: 255
            fixed: false
        description:
            type: text
            nullable: false
            length: 65535
            fixed: false
    lifecycleCallbacks: {  }
