Table11:
    type: entity
    table: 'TABLE 11'
    id:
        codeTransaction:
            type: string
            nullable: false
            length: 255
            fixed: false
            default: ''
            id: true
            column: 'CODE TRANSACTION'
            generator:
                strategy: IDENTITY
    fields:
        rib:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: RIB
        montant:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: MONTANT
        codeCommerce:
            type: string
            nullable: true
            length: 25
            fixed: false
            column: 'CODE COMMERCE'
        commerce:
            type: string
            nullable: true
            length: 40
            fixed: false
            column: COMMERCE
        dateEtHeure:
            type: string
            nullable: true
            length: 25
            fixed: false
            column: 'DATE ET HEURE'
    lifecycleCallbacks: {  }
